spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/autorep
    username: admin
    password: admin

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false

    show-sql: true


feign:
 client:
  config:
    default: 
      connectTimeout: 160000000
      readTimeout: 160000000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 200000

logging:
    level:
      #root: error
      org.springframwork: debug

#  h2:
#    console:
#      path: /h2-console
#      settings:
#        web-allow-others: true