spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/autorep
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false

    show-sql: true


  application:
    name: report-service

hibernate:
  temp:
    use_jdbc_metadata_defaults: false 

server:
  port: 9004
  

logging:
  level:
    #root: error
    org.springframwork: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"
