spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/autorep
    username: admin
    password: admin

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false

    show-sql: true

  application:
    name: user-service

server:
  port: 9005


logging:
  level:
    #root: error
    org.springframwork: debug


management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/